

# !!!!!!! !!!!!!! !!!!!!! !!!!!!! !!!!!!! !!!!!!! !!!!!!!
# This file is managed by Workspace.
# Manual changes will not persist.
# For more information, see:
# https://github.com/SDGGiesbrecht/Workspace/blob/master/Documentation/Continuous Integration.md
# !!!!!!! !!!!!!! !!!!!!! !!!!!!! !!!!!!! !!!!!!! !!!!!!!

language: generic
matrix:
  include:
    - os: osx
      env:
        - JOB="macOS"
      osx_image: xcode9
      script:
        - "bash ./Refresh\\ \\(macOS\\).command"
        - "bash ./Validate\\ \\(macOS\\).command"
    - os: linux
      dist: trusty
      env:
        - JOB="Linux"
        - SWIFT_VERSION=4.0
      script:
        - "eval \"$(curl -sL https://gist.githubusercontent.com/kylef/5c0475ff02b7c7671d2a/raw/9f442512a46d7a2af7b850d65a7e9bd31edfb09b/swiftenv-install.sh)\""
        - "bash ./Refresh\\ \\(macOS\\).command"
        - "bash ./Validate\\ \\(macOS\\).command"
    - os: osx
      env:
        - JOB="Misc."
      osx_image: xcode9
      script:
        - "brew update"
        - "brew outdated swiftlint || brew upgrade swiftlint"
        - "bash ./Refresh\\ \\(macOS\\).command"
        - "bash ./Validate\\ \\(macOS\\).command"

cache:
  directories:
  - $HOME/.Workspace
